### ISSUE TITLE
Examples does not work

### ISSUE THREAD

**Issue by zheoreh** [pilwon/node-ib#11]
I used first example from examples/all.js and it does not work.
I see next error:

@@@ ERROR: connect ECONNREFUSED @@@

Also I can not understand what are parameters in ib constructor. Can you explain it to me? And what is reqId in calculateImpliedVolatility?

-------------------------------------------
'use strict';

var util = require('util');

require('colors');

var _ = require('lodash');

var ib = new (require('..'))({
  // clientId: 0,
  // host: '127.0.0.1',
  // port: 7496
}).on('connected', function () {
  console.log('CONNECTED'.rainbow);
}).on('diconnected', function () {
  console.log('DISCONNECTED'.rainbow);
}).on('received', function (tokens) {
  console.info('%s %s', '<<< RECV <<<'.cyan, JSON.stringify(tokens));
}).on('sent', function (tokens) {
  console.info('%s %s', '>>> SENT >>>'.yellow, JSON.stringify(tokens));
}).on('server', function (version, connectionTime) {
  console.log(util.format('Server Version: %s', version).rainbow);
  console.log(util.format('Server Connection Time: %s', connectionTime).rainbow);
}).on('error', function (err) {
  console.error(util.format('@@@ ERROR: %s @@@', err.message).red);
}).on('result', function (event, args) {
  console.log(util.format('======= %s =======', event).green);
  args.forEach(function (arg, i) {
    console.log('%s %s',
      util.format('[%d]', i + 1).green,
      JSON.stringify(arg)
    );
  });
});

ib.connect();

ib.calculateImpliedVolatility(12345, {
  currency: 'USD',
  exchange: 'SMART',
  expiry: '20140118',
  right: 'C',
  secType: 'OPT',
  strike: 40.00,
  symbol: 'QQQQ'
}, 12.34, 56.78);  // reqId, contract, optionPrice, underPrice

===================================

**Comment by mike4242** [comment]
You need to set the port and host. And have the gateway running locally and connect on 127.0.0.1. Check in the gateway gui which port is used.
