### ISSUE TITLE
Can't Stream Futures Market Data Due to Inability to Specify Exchange

### ISSUE THREAD

**Issue by lewisdawson** [pilwon/node-ib#13]
When trying to steam futures market data through `reqMktData()`, such as the E-Mini S&P futures, you need the ability to specify the exchange. If you don't specify the exchange, you get a `Requested market data is not subscribed` error.

**Comment by lewisdawson** [comment]
I've opened pull request #14 to fix this issue.

**Comment by pilwon** [comment]
@lewisdawson Thanks, merged the PR and published as v0.1.4

**Comment by lewisdawson** [comment]
@pilwon Happy to help! Thanks creating the library.
