### ISSUE TITLE
Do the Scanners Subscriptions work?

### ISSUE THREAD

**Issue by lucky-lou** [pilwon/node-ib#139]
If so, how? I can't find any examples and reqScannerParameters function doesn't seem to do anything.

**Comment by nemozny** [comment]
Yes, the example is here `https://github.com/pilwon/node-ib/blob/master/examples/all.js`
If you reqScannerParameters and write it to a file, you will get XML, attached (had to ZIP it).
[scannerParams.zip](https://github.com/pilwon/node-ib/files/3516403/scannerParams.zip)

Actually the scanner works for STK, but I can't get it to work for FUT. I raised a ticket to IB, all I am getting is "You cannot combine locations from different regions.", which is a total nonsense.

I just asked for "FUT.US", nothing special.
I do have market data subscription at IB.

Did you have any luck with FUT anyone?

**Comment by nemozny** [comment]
Ok, my bad, it works. You just have to add FUT.US, not just FUT.

```
instrument: 'FUT.US',
locationCode: 'FUT.US'
```
You can close this ticket.
