### ISSUE TITLE
scanning

### ISSUE THREAD

**Issue by mdaymond** [pilwon/node-ib#15]
Is is possible to scan for stocks and options with the API ?

thanks!

**Comment by triploc** [comment]
This can be done by constructing a scanner using the reqScannerSubscription call with scanner parameters.  The scannerParameters event fires after a call to reqScannerParameters but does not seem to return the XML, though it is visibly returned (at least through the IB Gateway console).

**Comment by pilwon** [comment]
Thanks @triploc -
