### ISSUE TITLE
Always connects with Client ID 0 regardless of setting

### ISSUE THREAD

**Issue by andrewjdmartin** [pilwon/node-ib#17]
````
var ib = new ( require('ib') ) ({
	clientId: 1,
	host: '127.0.0.1',
	port: 7496
})
````
...will still connect with Client ID 0, per IB Gateway. Changing the host and port properties does have an effect. Noticed that line 78 of lib/socket.js doesn't specify the clientId:
````
  this._client = net.connect({
    host: this._controller.options.host,
    port: this._controller.options.port
  }, function () {
    self._onConnect.apply(self, arguments);
    self._controller.resume();
  });
````
...but adding it also had no effect. Any ideas? Thanks

**Comment by andrewjdmartin** [comment]
Replacing line 30 of lib/socket.js with:
````
this._client.write( C.CLIENT_VERSION + EOL );
this._client.write( this._controller.options.clientId + EOL );
````
...appears to work. Very likely a better way.

**Comment by lewisdawson** [comment]
@andrewjdmartin Did you test that your replacement solution works? I'm running into an issue when I try to use multiple client ids, so I'm curious if this solved it for you. I tried it, but it didn't work for me.

Looking at your proposal:

```
this._client.write( C.CLIENT_VERSION + EOL );
this._client.write( this._controller.options.clientId + EOL );
```

 vs. what's currently in the code:

```
this._controller.run('sendAsync', [C.CLIENT_VERSION, this._controller.options.clientId]);
```

They do the same thing. The `sendAsync` ultimately delegates back to `Socket.prototype.send` which does a `this._client.write()`:

```
Socket.prototype.send = function (tokens, async) {
  if (async) {
    this._waitingAsync = true;
    this._controller.pause();
  }

  tokens = _.flatten([tokens]);

  _.each(tokens, function (value, i) {
    if (_.isBoolean(value)) {
      tokens[i] = value ? 1 : 0;
    }
  });

  var data = tokens.join(EOL) + EOL;
  this._client.write(data);

  this._controller.emit('sent', tokens, data);

  this._neverSent = false;
};
```

**Comment by lewisdawson** [comment]
@pilwon I've opened pull request #19 to fix this issue.

**Comment by andrewjdmartin** [comment]
@lewisdawson Yeah, that's where I got the idea from. My experience in Node is quite limited, so I just tried doing the write() directly (and separately) to see if it would work. It did work for me, but I'm glad someone contributed a better solution. Thanks!

**Comment by pilwon** [comment]
@andrewjdmartin @lewisdawson Thanks for reporting this bug and finding a fix for it-
