### ISSUE TITLE
This repo is very outdated & misleading, everyone must move to https://github.com/stoqey/ib

### ISSUE THREAD

**Issue by ceddybi** [pilwon/node-ib#171]
@pilwon due to your inactivity on IB, please kindly advise everyone using this package to use https://github.com/stoqey/ib  instead.

Please stop leading people on if you cannot solve their problems, I mean, this repo has unresolved issues from 2016.

**Comment by pilwon** [comment]
Manners first.

**Comment by ceddybi** [comment]
@pilwon - well at least I have some, I mean where are all yours 😝😝😝

No offense man! - pull your socks up! otherwise, we're taking over!!!!

**Comment by tredondo** [comment]
@ceddybi why not @maxicus's [ib-tws-api](https://github.com/maxicus/ib-tws-api)?

**Comment by ceddybi** [comment]
@tredondo Heheh which one? 😶

 https://github.com/stoqey/ib is the super dope one!!!
