### ISSUE TITLE
Must this be used locally?

### ISSUE THREAD

**Issue by JohnAllen** [pilwon/node-ib#18]
Thought that either TWS or the API Gateway must be logged in to use IB's API.  So can this package NOT be used locally?

**Comment by ajpierce** [comment]
@JohnAllen This package can be used from anywhere, so long as TWS is configured to accept API connections from wherever you're running node-ib.

For example, if you've got TWS running on box `192.168.1.1`, and you want to run node-ib on box `192.168.1.2`, you need to configure TWS to accept API connections from `192.168.1.2`.

**Comment by pilwon** [comment]
Thanks @ajpierce
