### ISSUE TITLE
Requested market data is not subscribed.

### ISSUE THREAD

**Issue by mike4242** [pilwon/node-ib#21]
When I call reqMktData I get an error "Requested market data is not subscribed.Error&BEST/STK/Top&BEST/STK/Top". The account definitely has a market data subscription (Nasdaq and NYSE). I'm trying AAPL... still that error message. Have tried other stocks too. The gateway is running, connection OK. I am running the reqMktData.js example as is. Then tried just one stock, AAPL, still does not work.

The FAQ on IB's web page says: 

Q: Why do I receive an error 200 - No security definition has been found for the request when I call reqContractDetails, reqMktData, or addOrder() for a stock contract?

A: When using these methods for a stock contract, leave Global Symbol and Trading Class blank.

Am I supposed to change these? (if so, how) Or does the reqMktData call in node-ib handle that?

**Comment by mike4242** [comment]
This actually turned out to be my fault, the market data wasn't correctly configured. The example works fine. Thanks for the great lib, I'd love to contribute somehow if there's a need for it.

**Comment by pilwon** [comment]
@mike4242 Great to hear you found the solution. Always welcome community contributions :)

**Comment by jem890** [comment]
Hi @mike4242 ,  how did you manage to solve the issue? I am getting same error. 

Thanks a lot for the help.

**Comment by mike4242** [comment]
Start the gateway and deselect the option that says market data is read-only. If that doesn't work, then you're not subscribed to market data on the account you're using. If you have one real account and one paper trading account, then you need to share the data from the real account to the paper trading account.

**Comment by jem890** [comment]
Thanks for your quick response! I think it is because I am using a testing account.

**Comment by jdhurwitz** [comment]
@mike4242  I have one real account and one paper trading account. On my real account, I'm not subscribed to anything yet. Will I be unable to get this data in my paper trading account? All I want to do is run some sims...I can't do this unless I pay?

**Comment by jdhurwitz** [comment]
@jem890  Did you figure out this problem?
