### ISSUE TITLE
placeOrder not working version v0.1.7 API (TWS Build 955.2g)

### ISSUE THREAD

**Issue by joelpinheiro** [pilwon/node-ib#24]
Hi,

First, congrats for this API. 

I'm trying to call placeOrder and I have this output:

`$ node placeOrder.js
managedAccounts: ["DU317663"]
[nextValidId] orderId=1
Placing orders...
Market data farm connection is OK:cashfarm
Market data farm connection is OK:usfarm.us
Market data farm connection is OK:usfarm
HMDS data farm connection is OK:fundfarm
HMDS data farm connection is OK:ushmds
[nextValidId] orderId=1
Error validating request:-'ke' : cause - You must specify an account.
Error validating request:-'ke' : cause - You must specify an account.
Error validating request:-'ke' : cause - You must specify an account.
[openOrderEnd]
[nextValidId] orderId=1
Cancelling orders...
Can't find order with id =1
Can't find order with id =2
Can't find order with id =3
[openOrderEnd]
Disconnecting...`

When I call placeOrder there is no response from the server.

Should I specify which account I want to placeOrder?
How can I do that?

Regards

**Comment by joelpinheiro** [comment]
Changing the account in TWS fix it. Dunno why.

**Comment by joelpinheiro** [comment]
Anybody knows why this error happen?
`Error validating request:-'ke' : cause - You must specify an account.`

With the exactly same code it works well in demo account, but, with the account I've created it don't.

**Comment by lewisdawson** [comment]
@joelpinheiro Do you have a code example?

**Comment by okonovalenko** [comment]
u might need to add account property to your order object?
order.account = 'DU317663'
placeOrder(-1, contract, order);
