### ISSUE TITLE
Can I trade all security type using node-ib?

### ISSUE THREAD

**Issue by closelate** [pilwon/node-ib#46]
HI, Guys,
Does node-ib support security type like 
```
BOND
CASH          
CFD
FOP
WAR
IOPT
FWD
BAG
IND
BILL
FUND
FIXED
SLB
NEWS
CMDTY
BSK
ICU
```
other than STK, FUT and OPT?

**Comment by buzzcloudau** [comment]
IND and FOP were recently added, but no examples yet.

IND : https://github.com/pilwon/node-ib/pull/37
FOP : https://github.com/pilwon/node-ib/pull/39

It is easy enough to extend to add new security types. Just create a supporting file in /lib/contract/ with the defaults, then add the reference in /lib/contract/index.js

**Comment by closelate** [comment]
Thank you buzzcloudau!
