### ISSUE TITLE
TIme In Force (tif) question

### ISSUE THREAD

**Issue by closelate** [pilwon/node-ib#47]
Where do I enter tif (time in force) when I place order,
I modified the stock.js like the following:

``` js
module.exports = function (symbol, exchange, currency, tif) {
  assert(_.isString(symbol), 'Symbol must be a string.');

  return {
    currency: currency || 'USD',
    exchange: exchange || 'SMART',
    secType: 'STK',
    symbol: symbol,
    tif: tif
  };
};
```

Is this going to work?
Thanks

**Comment by nemozny** [comment]
TIF is an order(.js) property, not contract(.js). 
Please see
#110 

You can close this issue.
