### ISSUE TITLE
Feature to control messages per second

### ISSUE THREAD

**Issue by claude2** [pilwon/node-ib#49]
When I send many requests, I get this error:

> Max rate of messages per second has been exceeded:max=50 rec=108

**Comment by junajan** [comment]
Hi @claude2  .. you can use some throttling module which is available on npm.. 

This article is in czech language but look on the code - there is an example how to limit requests per second in node.js- http://www.janjuna.cz/blog/node-js-javascript/624-throttling-zpomalovani-api-requestu-v-node-js/
