### ISSUE TITLE
Buying on margin

### ISSUE THREAD

**Issue by junajan** [pilwon/node-ib#51]
Hello guys.. It is maybe lame question but .. how can I buy something on margin?

For example if I want to buy 3x leveraged AAPL CFD..

**Comment by lewisdawson** [comment]
If you have a IB margin account, they "automatically" apply the margin in that you don't need to cover the full price of the security to take a position on it. Take a look [here](https://www.interactivebrokers.com/en/index.php?f=marginnew&p=overview).

**Comment by junajan** [comment]
Thx.. I discovered, that if you have a margin or t-reg account you just trade with more money (eg. 3x more) and as you said IB will handle it automatically so it does not need to be implemented in the code. Thx for your reply :sunny:
