### ISSUE TITLE
clientId single digit issue

### ISSUE THREAD

**Issue by amcintyre99** [pilwon/node-ib#54]
When I try using different single digit clientIds, IB gateway refuses connection because of duplicate clientIds. So trying 0, 1, 2 at the same time gets an error because IB sees them all as 0.

However, if I start with 10, 11, 12, etc., it works ok since IB gateway sees them as 0, 1, 2 and so on.

So there is a work around but thought I would let you know about this.

thanks!!

**Comment by amcintyre99** [comment]
I was at your 1.9 and found this
https://github.com/pilwon/node-ib/issues/17

so upgraded to your 1.10 but still have same issue.

**Comment by amcintyre99** [comment]
upgraded to your 1.11 and still have issue with both TWS and IB gateway

**Comment by buzzcloudau** [comment]
I can confirm this behaviour in TWS, but the gateway seems to be working fine for me.

**Comment by claude2** [comment]
[Issue](https://github.com/pilwon/node-ib/issues/27#issuecomment-278593418) still exists in v0.1.18.
