### ISSUE TITLE
Doesn't work with Webpack

### ISSUE THREAD

**Issue by claude2** [pilwon/node-ib#75]
Basic Webpack config, getting this error:

> ERROR in ../~/ib/lib/socket.js
> Module not found: Error: Can't resolve 'net' in './node_modules/ib/lib'

Applying the "fix" suggested [here](https://github.com/request/request/issues/1529#issuecomment-103454943) doesn't work because `ib.connect()` actually needs `net`.

**Comment by pilwon** [comment]
Closing this issue. Please follow #76.

**Comment by claude2** [comment]
With 0.1.16 and a basic Webpack config, I get

> Uncaught TypeError: net.connect is not a function(…)

webpack.config.js:

```js
module.exports = {
  entry: ['./ibtest.js'],

  output: {
    publicPath: '/',
    filename: './bundle.js'
  },
  devtool: 'source-map',
  node: {
    net: 'empty',  // webpack error without this, Can't resolve 'net' in './node_modules/ib/lib'
  }
};
```

**Comment by pilwon** [comment]
@claude2 Webpack's default build target is `web` and the error occurs because `net` module only exists in Node.js. Try adding these two options to your webpack config:

```js
{
  libraryTarget: 'commonjs2',
  target: 'node',
}
```

**Comment by claude2** [comment]
I added this:

```js
module: {
  loaders: [
    {
      loader: 'babel',
      test: /\.js$/,
      exclude: /node_modules/
    },

    {
       loader: 'json-loader',
       test: /\.json$/
     }

  target: 'node',
  output: {
    libraryTarget: 'commonjs2',
    // ...
  },
```

webpack-dev-server gives a warning:

> WARNING in ../~/encoding/lib/iconv-loader.js
9:12 Critical dependency: the request of a dependency is an expression

In the browser I get

> bundle.js:1Uncaught ReferenceError: module is not defined(…)

Tried `libraryTarget: 'commonjs2'`, got

> bundle.js:1Uncaught ReferenceError: exports is not defined(…)

Without it at all, I get

> external "url":1Uncaught ReferenceError: require is not defined(…)

**Comment by pilwon** [comment]
@claude2 Would you be able to create a sample repo for what you've tried?

**Comment by claude2** [comment]
https://github.com/claude2/ib-webpack

Thanks for looking at this @pilwon

**Comment by pilwon** [comment]
@claude2 Hmm... I'm not getting any error message even when [these lines are removed from webpack config file](https://github.com/claude2/ib-webpack/blob/master/webpack.config.js#L10-L12) What version of Node do you use?

```
$ webpack
Hash: c97d72f5098e76a980a4
Version: webpack 2.1.0-beta.27
Time: 1986ms
          Asset     Size  Chunks             Chunk Names
    ./bundle.js  1.14 MB       0  [emitted]  main
./bundle.js.map   1.4 MB       0  [emitted]  main
   [5] ./index.js 886 bytes {0} [built]
  [41] multi main 28 bytes {0} [built]
    + 40 hidden modules
```

**Comment by claude2** [comment]
node 7.2.1 but the error is in the browser console:

> Uncaught ReferenceError: module is not defined
    at bundle.js:1

With or without the `node: {net: 'empty'}` lines.

**Comment by pilwon** [comment]
@claude2 I'm afraid we cannot run `node-ib` as is in Chrome unless we use something like [chrome-net](https://github.com/feross/chrome-net)
