### ISSUE TITLE
Get market data for index

### ISSUE THREAD

**Issue by claude2** [pilwon/node-ib#87]
How can I get market data for an index? The index constructor requires expiration, but many indexes don't have expiration e.g. VIX. I tried this but no market data arrives:

```js
ib.contract.index('VIX', '', 'USD', 'CBOE')
```

CC @buzzcloudau

**Comment by buzzcloudau** [comment]
For the date, I use the current date.

this may help to get the current date in the right format

     getYYYYMMDD = function () {

		var timestamp = ib.getExchangeDate();
		var yyyy = timestamp.getUTCFullYear().toString();
		var mm = (timestamp.getUTCMonth()+1).toString(); 
		var dd = timestamp.getUTCDate().toString();

		return ( yyyy + (mm[1]?mm:"0"+mm[0]) + (dd[1]?dd:"0"+dd[0]) );	

	};

**Comment by claude2** [comment]
I don't see `getExchangeDate()` in the library docs or in IB API, is it a custom method?

**Comment by buzzcloudau** [comment]
Sorry, it is a custom method.

	process.env.TZ = 'America/New_York';

...

	ib.getExchangeDate = function() {

		var timestamp = new Date();

		timestamp.setUTCDate(timestamp.getDate());
		timestamp.setUTCMonth(timestamp.getMonth());
		timestamp.setUTCHours(timestamp.getHours());
		timestamp.setUTCMinutes(timestamp.getMinutes());

		return timestamp;

	}

**Comment by claude2** [comment]
@buzzcloudau: I added this line to [the reqMktData example](https://github.com/pilwon/node-ib/pull/90)

    ib.reqMktData(2, ib.contract.index('VIX', '20170212', 'USD', 'CBOE'), '', false);

Today is 20170212. No data arrived from IB for VIX. I removed the other stock/option/future requests to make sure, still no data for VIX. @pilwon, help?

**Comment by buzzcloudau** [comment]
This will only return data while the symbol is trading. So between 9:30am and 4:00pm when the market is open.

**Comment by claude2** [comment]
I see data right now, 02:45 AM Chicago time (CST). IB Contract Description:

> Trading Hours: February 13, 2017
> Total Available Hours
> 02:00 CST - 08:15 CST (00:00 PST - 06:15 PST)
> 08:30 CST - 15:15 CST (06:30 PST - 13:15 PST)

This is annoying. AAPL had data even during the weekend and has data right now (`[CLOSE] price=132.12`), but AAPL trading doesn't start until 04:00 EST:

> Trading Hours: February 13, 2017
> Regular Trading Session
> 09:30 EST - 16:00 EST (06:30 PST - 13:00 PST)    
> Total Available Hours
> 04:00 EST - 20:00 EST (01:00 PST - 17:00 PST)

**Comment by claude2** [comment]
If you request data during trading hours, no date needs to be passed to the VIX contract, this works:

    ib.reqMktData(2, ib.contract.index('VIX', '', 'USD', 'CBOE'), '', false);
