### ISSUE TITLE
RTVolume

### ISSUE THREAD

**Issue by geewhizkid** [pilwon/node-ib#98]
New to Node.js and new to IB.

Can a call be added to get RTVolume?  Is this something I can contribute, and if so, are there any docs or guides to the socket messages received from IB?

**Comment by meteorpublish** [comment]
This works already. Just `reqMarketData` with `genericTickList: 233`:

```js
ib.reqMktData(
      someTickerId,
      contract,
      '233',  // genericTickList: RTVolume - https://interactivebrokers.github.io/tws-api/tick_types.html#rt_volume
      false,  // snapshot
      false,  // regulatorySnapshot,
    );
```

Then in the listener, look for [tickType 48](https://interactivebrokers.github.io/tws-api/tick_types.html#rt_volume).

@pilwon, feel free to close
